In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('English.csv')
df

                                  English words/sentences
0                                                     Hi.
1                                                    Run!
2                                                    Run!
3                                                    Who?
4                                                    Wow!
...                                                   ...
175616  Top-down economics never works, said Obama. "T...
175617  A carbon footprint is the amount of carbon dio...
175618  Death is something that we're often discourage...
175619  Since there are usually multiple websites on a...
175620  If someone who doesn't know your background sa...

[175621 rows x 1 columns]

In [ ]:
!pip3 install googletrans==3.1.0a0

Collecting googletrans==3.1.0a0
  Downloading googletrans-3.1.0a0.tar.gz (19 kB)
Collecting httpx==0.13.3
  Downloading httpx-0.13.3-py3-none-any.whl (55 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 55 kB 2.1 MB/s
Collecting sniffio
  Downloading sniffio-1.2.0-py3-none-any.whl (10 kB)
Requirement already satisfied: idna==2.* in /usr/local/lib/python3.7/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0) (2.10)
Collecting hstspreload
  Downloading hstspreload-2021.12.1-py3-none-any.whl (1.3 MB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1.3 MB 11.1 MB/s
Collecting httpcore==0.9.*
  Downloading httpcore-0.9.1-py3-none-any.whl (42 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 42 kB 1.4 MB/s
Requirement already satisfied: chardet==3.* in /usr/local/lib/python3.7/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0) (3.0.4)
Collecting rfc3986<2,>=1.3
  Downloading rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0) (2021.10.8)
Collecting h11<0.10,>=0.8
  Downloading h11-0.9.0-py2.py3-none-any.whl (53 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 53 kB 1.8 MB/s
Collecting h2==3.*
  Downloading h2-3.2.0-py2.py3-none-any.whl (65 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 65 kB 3.5 MB/s
Collecting hyperframe<6,>=5.2.0
  Downloading hyperframe-5.2.0-py2.py3-none-any.whl (12 kB)
Collecting hpack<4,>=3.0
  Downloading hpack-3.0.0-py2.py3-none-any.whl (38 kB)
Building wheels for collected packages: googletrans
  Building wheel for googletrans (setup.py) ... done
  Created wheel for googletrans: filename=googletrans-3.1.0a0-py3-none-any.whl size=16367 sha256=8a40e8999fdbbf6ea5c4a2a6bfb23f71b2afb13b0de27aaa5b7bb853eb7fa343
  Stored in directory: /root/.cache/pip/wheels/0c/be/fe/93a6a40ffe386e16089e44dad9018ebab9dc4cb9eb7eab65ae
Successfully built googletrans
Installing collected packages: hyperframe, hpack, sniffio, h2, h11, rfc3986, httpcore, hstspreload, httpx, googletrans
Successfully installed googletrans-3.1.0a0 h11-0.9.0 h2-3.2.0 hpack-3.0.0 hstspreload-2021.12.1 httpcore-0.9.1 httpx-0.13.3 hyperframe-5.2.0 rfc3986-1.5.0 sniffio-1.2.0

In [ ]:
from googletrans import Translator
translator = Translator()
#translator.translate('hi my name is akash', dest='es').text
df['french'] = [translator.translate(str(r), dest='fr').text for r in df['English words/sentences']]

In [ ]:
df

,English words/sentences,french
0,Hi.,Salut.
1,Run!,Cours!
2,Run!,Cours!
3,Who?,Qui?
4,Wow!,Ouah!
...,...,...
175616,"Top-down economics never works, said Obama. ""T...","L'Ã©conomie descendante ne fonctionne jamais, a..."
175617,A carbon footprint is the amount of carbon dio...,Une empreinte carbone est la quantitÃ© de pollu...
175618,Death is something that we're often discourage...,La mort est quelque chose dont nous sommes sou...
175619,Since there are usually multiple websites on a...,Comme il existe gÃ©nÃ©ralement plusieurs sites W...
175620,If someone who doesn't know your background sa...,Si quelqu'un qui ne connaÃ®t pas vos antÃ©cÃ©dent...

In [ ]:
from googletrans import Translator
translator = Translator()
#translator.translate('hi my name is akash', dest='es').text
df['spanish'] = [translator.translate(str(r), dest='es').text for r in df['English words/sentences']]

In [ ]:
df1= df.head(50000)

In [ ]:
df1

       English words/sentences
0                          Hi.
1                         Run!
2                         Run!
3                         Who?
4                         Wow!
...                        ...
49995  Tell us all the gossip.
49996  Ten years have gone by.
49997  Tennis is loads of fun.
49998  Thank you all for that.
49999  Thank you ever so much.

[50000 rows x 1 columns]

In [ ]:
from googletrans import Translator
translator = Translator()
#translator.translate('hi my name is akash', dest='es').text
df1['french'] = [translator.translate(str(r), dest='fr').text for r in df1['English words/sentences']]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [ ]:
df1

       English words/sentences                       french
0                          Hi.                       Salut.
1                         Run!                       Cours!
2                         Run!                       Cours!
3                         Who?                         Qui?
4                         Wow!                        Ouah!
...                        ...                          ...
49995  Tell us all the gossip.  Dites-nous tous les potins.
49996  Ten years have gone by.           Dix ans ont passÃ©.
49997  Tennis is loads of fun.  Le tennis est trÃ¨s amusant.
49998  Thank you all for that.      Merci Ã  tous pour cela.
49999  Thank you ever so much.            Merci infiniment.

[50000 rows x 2 columns]